// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTuLm2CKHeLZ2O-6gpjMltwPzWatdG0wI',
    appId: '1:693568913009:web:3db7b370bd7afeca0e25d0',
    messagingSenderId: '693568913009',
    projectId: 'shopingyou-64e8e',
    authDomain: 'shopingyou-64e8e.firebaseapp.com',
    storageBucket: 'shopingyou-64e8e.appspot.com',
    measurementId: 'G-WZ4JE1Y47D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQZCBOD9r-KCsqv-g4Op4xZArbxpuK318',
    appId: '1:693568913009:android:4513911866b1f2140e25d0',
    messagingSenderId: '693568913009',
    projectId: 'shopingyou-64e8e',
    storageBucket: 'shopingyou-64e8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA69_nMgem4h9fhKuVb-yoaI93XPLC3E7o',
    appId: '1:693568913009:ios:4f71ce0cf8ef2b8c0e25d0',
    messagingSenderId: '693568913009',
    projectId: 'shopingyou-64e8e',
    storageBucket: 'shopingyou-64e8e.appspot.com',
    iosBundleId: 'com.example.shoppingyou',
  );
}
